export { default as Modal } from "./ui/Modal.jsx";
export { default as ProjectModal } from "./ui/ProjectModal.jsx";
export { default as RoleSelectionModal } from "./ui/RoleSelectionModal.jsx";
export { default as LoadingSpinner } from "./ui/LoadingSpinner.jsx";
export { default as ErrorMessage } from "./ui/ErrorMessage.jsx";
export { default as Pagination } from "./ui/Pagination.jsx";
export { default as ScrollToTop } from "./ui/ScrollToTop.jsx";
export { default as ParticleSystem } from "./ui/ParticleSystem.jsx";
export { default as AppBackground } from "./ui/backgrounds/AppBackground.jsx";

export { PatternBackground, PATTERN_PRESETS, PATTERN_VARIANTS, VINTAGE_NEUBRUTAL_PATTERN_VARIANTS } from "./ui/patterns";
export { useSound } from "./hooks/useSound.js";
export { useBackendKeepAlive } from "./hooks/useBackendKeepAlive.js";
export { default as useAboutModalGsapAnimation } from "./hooks/useAboutModalGsapAnimation.js";
export { useModalAnimation, overlayVariants, panelSlideDown } from "./hooks/useModalAnimation.js";
export { useScrollReveal, revealVariants } from "./hooks/useScrollReveal.js";
export { default as Lightbox } from "./ui/Lightbox/Lightbox.jsx";
export { default as BeforeAfterSlider } from "./ui/BeforeAfterSlider/BeforeAfterSlider.jsx";
export { default as Reveal } from "./ui/Reveal/Reveal.jsx";
export { default as CodeSnippet } from "./ui/CodeSnippet/CodeSnippet.jsx";
export { default as HoverVideo } from "./ui/HoverVideo/HoverVideo.jsx";
export { default as ErrorBoundary } from "./ui/ErrorBoundary/ErrorBoundary.jsx";
export { Button, Card, Tag, Container, Stack, Grid, Section, Input, SearchInput, Textarea, Select, Field } from "./design-system/index.js";
